name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the last two commits

    - name: Configure AWS credentials from OpenID Connect
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::471112860139:role/release-notes-role-gh-actions
        aws-region: us-west-2

    - name: Get list of changed files
      id: changes
      run: |
        git diff --name-status HEAD^ HEAD > changes.log
        cat changes.log

    - name: Compare files using MD5 hash and detect changes
      id: detect_changes
      run: |
        # Compare file content using md5sum
        for file in $(find ./addons -type f); do
          local_md5=$(md5sum "$file" | cut -d' ' -f1)
          s3_md5=$(aws s3api head-object --bucket persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki --key "$(basename $file)" --query 'ETag' --output text | tr -d '"')

          if [ "$local_md5" != "$s3_md5" ]; then
            echo "File changed: $file"
            echo "$file" >> files_to_upload.txt
          fi
        done

    - name: Detect renames and deletions
      run: |
        # Detect renamed or deleted files
        while read status file; do
          if [[ "$status" == "R"* ]]; then
            echo "File renamed: $file"
            aws s3 rm s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $file)
          elif [[ "$status" == "D" ]]; then
            echo "File deleted: $file"
            aws s3 rm s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $file)
          fi
        done < changes.log

    - name: Preview changes
      run: |
        if [[ -f files_to_upload.txt ]]; then
          echo "Files to upload:"
          cat files_to_upload.txt
        else
          echo "No files to upload."
        fi

    - name: Upload changed files to S3
      run: |
        if [[ -f files_to_upload.txt ]]; then
          while read file; do
            aws s3 cp "$file" s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/ --metadata-directive REPLACE
          done < files_to_upload.txt
        fi
