name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials from OpenID Connect
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::471112860139:role/release-notes-role-gh-actions
        aws-region: us-west-2

    - name: List changed files
      id: changed_files
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/main
        git diff --name-only HEAD^ HEAD > changed_files.txt
        cat changed_files.txt

    - name: Sync changed files to S3
      run: |
        while read file; do
          aws s3 cp "$file" "s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$file"
        done < changed_files.txt
