name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the last two commits

    - name: Configure AWS credentials from OpenID Connect
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::471112860139:role/release-notes-role-gh-actions
        aws-region: us-west-2

    - name: Check if S3 bucket is empty
      id: s3_check
      run: |
        # List objects in the S3 bucket and check if it's empty
        OBJECTS=$(aws s3api list-objects --bucket persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki --query 'Contents' --output text)
        if [[ -z "$OBJECTS" ]]; then
          echo "Bucket is empty"
          echo "::set-output name=bucket_status::empty"
        else
          echo "Bucket is not empty"
          echo "::set-output name=bucket_status::not_empty"
        fi

    - name: First-time upload (if bucket is empty)
      if: steps.s3_check.outputs.bucket_status == 'empty'
      run: |
        echo "Uploading all contents of addons directory as bucket is empty."
        aws s3 cp --recursive ./addons/ s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/

    - name: Get list of changed files in addons directory
      id: changes
      run: |
        # Only track changes in the addons directory
        git diff --name-status HEAD^ HEAD -- addons/ > changes.log
        cat changes.log

    - name: Handle file changes (add, modify, rename, delete) in addons directory only
      if: steps.s3_check.outputs.bucket_status == 'not_empty'
      run: |
        # Loop through the diff log to identify changes in the addons directory
        while read status file; do
          # Ensure the file is within the addons directory
          if [[ "$file" == addons/* ]]; then
            case "$status" in
              A)  # File added
                  echo "Adding file: $file"
                  aws s3 cp "$file" s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $file)
                  ;;
              M)  # File modified
                  echo "Modifying file: $file"
                  aws s3 cp "$file" s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $file) --metadata-directive REPLACE
                  ;;
              R*) # File renamed
                  old_file=$(echo "$file" | cut -f1)
                  new_file=$(echo "$file" | cut -f2)
                  echo "Renaming file from $old_file to $new_file"
                  aws s3 rm s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $old_file)
                  aws s3 cp "$new_file" s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $new_file)
                  ;;
              D)  # File deleted
                  echo "Deleting file: $file"
                  aws s3 rm s3://persistentstack-us-west-2-releasenotesbucketdbdb4f-pys20oqkdpki/$(basename $file)
                  ;;
              *)  # Skip unrecognized statuses
                  echo "Unknown status $status for file $file"
                  ;;
            esac
          fi
        done < changes.log

    - name: Preview changes
      run: |
        echo "Showing all changes in addons directory"
        cat changes.log
